<a href="https://colab.research.google.com/github/gurramlekhana2/DAA/blob/main/NumPy_HandsOn_Array_to_Image_Analysis_Student_Lab_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Hands-on Lab: From Arrays to Image Analysis

## Student Practice Notebook

**Name:** ___________Gurram Lekhana___________  
**Register Number:** AP24110010760

**Date:** 15 aug 2026

## Learning Objectives

After completing this lab, you will be able to:

- Create and manipulate NumPy arrays
- Understand array properties and dimensions
- Perform indexing and slicing
- Apply mathematical operations
- Understand and explain broadcasting
- Analyze images using NumPy arrays
- Perform basic image transformations
- Explain *why* NumPy is used in real ML/Data Science pipelines, not just *how*

### How to use this notebook
- **Demonstration** cells: run them, read the output, understand it.
- **Practice** cells: write your own code — don't copy the demo verbatim.
- **Predict-then-run**: before running some cells, you'll be asked to *predict* the output first. Write your prediction in the markdown cell, then run and compare.
- **Reflection**: short written answers, in your own words.


## Part 1: Introduction to NumPy

NumPy (Numerical Python) is a Python library used for efficient numerical computation.

**Why not just use Python lists?** Python lists store objects with overhead per element and loop in pure Python. NumPy arrays store raw numbers in contiguous memory and use compiled C code for operations — this is called **vectorization**. That's why NumPy is used everywhere in:

- Data Science (pandas is built on NumPy)
- Machine Learning (feeding data into models as arrays/tensors)
- Image Processing (an image *is* a NumPy array)
- Scientific Computing

Let's actually *see* the speed difference before we take it on faith.


In [ ]:
import numpy as np #AP24110010760
import matplotlib.pyplot as plt
print("NumPy is ready!")


NumPy is ready!


### Demonstration: Loops vs. Vectorization (the "why" behind NumPy)

Below we add 1 to a million numbers two ways: a plain Python loop, and a NumPy array operation.
Run this cell and look at the timing output.


In [ ]:
import time
n = 1_000_000
python_list = list(range(n))
numpy_array = np.arange(n)
start = time.time()
result_list = [x + 1 for x in python_list]
loop_time = time.time() - start
start = time.time()
result_array = numpy_array + 1
vector_time = time.time() - start
print(f"Python loop time : {loop_time:.5f} seconds")
print(f"NumPy vector time: {vector_time:.5f} seconds")
print(f"NumPy was about {loop_time/vector_time:.0f}x faster")#AP24110010760


Python loop time : 0.10915 seconds
NumPy vector time: 0.00718 seconds
NumPy was about 15x faster


**Reflection (write your answer):** Based on the timing above, in your own words, why is NumPy faster than a Python loop for this kind of operation?

*Your answer:*NumPy is faster than a Python as it performs operations on entire arrays at once using optimized code. Instead of processing each element one by one in Python, NumPy uses efficient low-level operations, which reduces the time needed to perform calculations.#AP24110010760



## Part 2: Creating NumPy Arrays

### Demonstration

In [ ]:
arr = np.array([10,20,30,40,50])
arr#AP24110010760


array([10, 20, 30, 40, 50])

### Student Practice

Create an array containing:

5, 10, 15, 20, 25

Write your code below (do not just copy the demo — change the numbers yourself):


In [ ]:
import numpy as np
arr=np.array([5,10,15,20,25])
arr
#AP24110010760


array([ 5, 10, 15, 20, 25])

numpy is a standard python library which is used for numerical computation for effeective access#AP24110010760

## Part 3: Array Properties

Important properties:

- `ndim` : Number of dimensions
- `shape` : Size of each dimension
- `size` : Total number of elements
- `dtype` : Data type

**Predict first:** for the array `arr` from Part 2, what do you *expect* `ndim`, `shape`, `size`, and `dtype` to be? Write your guess below before running the next cell.

*Your prediction:*


In [ ]:
arr.ndim, arr.shape, arr.size, arr.dtype


(1, (5,), 5, dtype('int64'))

### Observation

Was your prediction correct? If not, what did you get wrong and why?

Dimension:1

Shape:(5,)

Size:5

Data Type:int


## Part 4: Special Arrays

These are commonly used to initialize data — for example, `zeros` is often used to create an empty "canvas" array before filling in real values (you'll see this again in the image section).


In [ ]:
np.zeros((3,3))


array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.eye(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Student Practice

Create a `5x5` array of all zeros, and a `2x6` array of all ones. Write both below.


In [ ]:
#AP24110010760
np.zeros((5,5))



array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

spl arrays used to print zeros where 5 is rows and 5 is columns

In [ ]:
np.ones((2,6)) #AP24110010760

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

spl arrays used to print ones where 2 is rows and 6 is columns

## Part 5: Sequence Generation

In [ ]:
np.arange(0,50,5)


array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [ ]:
np.linspace(0,100,10)


array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

### Student Practice

`np.arange` and `np.linspace` both generate sequences but work differently.

1. Use `np.arange` to generate even numbers from 2 to 20.
2. Use `np.linspace` to generate 5 evenly spaced numbers between 0 and 1.
3. In one sentence, write the difference between `arange` (step-based) and `linspace` (count-based).


In [ ]:
# AP24110010760
np.arange(2,20,2)


array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

used to range the numbers (start,stop,step) similar to for loop

In [ ]:
arr = np.linspace(0, 1, 5)
print(arr)#AP24110010760

[0.   0.25 0.5  0.75 1.  ]


np.arange() gives numbers based on a given step size, where np.linspace() gives a specific number of evenly spaced values between a starting and ending point.

## Part 6: Random Numbers

In [ ]:
np.random.rand(5)


array([0.40179335, 0.72890741, 0.28353067, 0.55951527, 0.17768492])

In [ ]:
np.random.randint(1,100,10)


array([23, 85, 29, 85, 17, 73, 44, 34, 97, 73])

## Part 7: Reshaping Arrays

Reshape changes the *structure* of an array without changing the data.

**Rule: the total number of elements must stay the same.** `3x4 = 12` elements, so you can reshape into any combination of dimensions that multiplies to 12 (e.g. `2x6`, `4x3`, `1x12`, `12x1`).


In [ ]:
a = np.arange(12)#AP24110010760
a.reshape(3,4)


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

### Student Practice — valid shapes

Try reshaping `a` into these shapes. Write each as a separate line:
- 2 x 6
- 4 x 3
- 6 x 2


In [ ]:
# AP24110010760
a=np.arange(12)
a.reshape(2, 6)


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [ ]:
a.reshape(4, 3)#AP24110010760

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
a.reshape(6, 2)#AP24110010760

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### Student Practice — break it on purpose

Now try `a.reshape(5,3)`. This should throw an error because 5 × 3 = 15 ≠ 12.

Run it, read the error message, then answer: **why did it fail, and what rule does it confirm about reshape?**

*Your answer:*


In [ ]:
# Try the invalid reshape here and observe the error
#AP24110010760
a.reshape(5, 3)

ValueError: cannot reshape array of size 12 into shape (5,3)

cant do this cause no of elemnts in the array are less than 5*3 so numpy cant do like fitting small no of elemts in large spaces and while reshaping number should be equal to no of elements in array

## Part 8: Indexing and Slicing

In [ ]:
import numpy as np
matrix = np.arange(1,10).reshape(3,3)#AP24110010760
matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Extract first row
matrix[0]#AP24110010760


array([1, 2, 3])

In [ ]:
# Extract first column
matrix[:,0]#AP24110010760


array([1, 4, 7])

### Student Practice

Using `matrix` above, write code to extract:
1. The last row
2. The last column
3. The single element in the middle (row 1, column 1)
4. The bottom-right 2x2 sub-matrix


In [ ]:
# AP24110010760
import numpy as np
matrix = np.arange(1, 10).reshape(3, 3)
print(matrix)
matrix[-1]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

to extract the last row

In [ ]:
matrix[:, -1]#AP24110010760

array([3, 6, 9])

to extract last column

In [ ]:
matrix[1, 1]#AP24110010760

np.int64(5)

Extract the single element in the middle (row 1, column 1)

In [ ]:
matrix[1:3, 1:3]#AP24110010760

array([[5, 6],
       [8, 9]])

Extract the bottom-right 2×2 sub-matrix

## Part 9: Mathematical Operations

In [ ]:
marks = np.array([60,70,80,90])#AP24110010760

marks + 5


array([65, 75, 85, 95])

In [ ]:
marks * 2
#AP24110010760

array([120, 140, 160, 180])

### Student Practice

A student scored `marks = [55, 62, 48, 91, 73]` but every question was later found to be worth 1 extra bonus mark, and then the whole test was scaled to be out of 150 (currently out of 100, so multiply by 1.5).

Write the NumPy code to: (1) add the bonus mark to every score, then (2) scale to out of 150.


In [ ]:
# AP24110010760
import numpy as np
marks = np.array([55, 62, 48, 91, 73])
marks = marks + 1

to add one mark bonus

In [ ]:
marks = marks * 1.5#AP24110010760

multiplying

In [ ]:
print(marks)#AP24110010760

[ 84.   94.5  73.5 138.  111. ]


## Part 10: Broadcasting

Broadcasting lets NumPy perform operations between arrays of **different shapes**, without writing an explicit loop, by "stretching" the smaller array to match the larger one — as long as their shapes are compatible.

**The basic rule:** starting from the trailing (rightmost) dimension, two dimensions are compatible if they're equal, or one of them is 1. NumPy then virtually repeats the size-1 dimension to match.

You already used broadcasting in Part 9 (`marks + 5`) — a single number (shape `()`) was broadcast across the whole array. Here's a less obvious example: a 1D array broadcast across a 2D array.


In [ ]:
salary = np.array([30000,40000,50000])

salary * 1.10#AP24110010760


array([33000., 44000., 55000.])

In [ ]:
# A less obvious broadcasting example: adding a 1D array to every row of a 2D array
grid = np.ones((3,3))       # shape (3,3)
row_bonus = np.array([1,2,3])  # shape (3,)

grid + row_bonus#AP24110010760


array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

### Student Practice — predict then check

Before running the next cell, predict the output shape and values on paper.

`np.array([[1],[2],[3]]) + np.array([10,20,30])`

(Hint: one array has shape `(3,1)`, the other `(3,)`. Think about how each dimension aligns.)

*Your prediction:*


In [ ]:
# AP24110010760
np.array([[1],[2],[3]]) + np.array([10,20,30]) #AP24110010760


array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

**Reflection:** In your own words, explain broadcasting with an example of your own (not one from this notebook).

*Your answer:*Broadcasting  means performing an operation on arrays with different shapes by  adjusting the smaller array to match the larger one. For example, if I have a 2×3 array `[[1, 2, 3], [4, 5, 6]]` and add `[10, 20, 30]`, NumPy adds the values to each row, giving `[[11, 22, 33], [14, 25, 36]]`. This makes array calculations simple without manually repeating the smaller array.



## Part 11: Filtering Data (Boolean Indexing)

In [ ]:
marks = np.array([45,67,89,32,90,55])

marks[marks > 60]#AP24110010760


array([67, 89, 90])

### Student Practice

Using the `marks` array above:
1. Extract all marks that are failing (below 40).
2. Count how many students scored above 80 (hint: `.sum()` on a boolean array counts `True` values).
3. Replace all failing marks with 0 using `np.where`.


In [ ]:
marks = np.array([45,67,89,32,90,55])

marks[marks > 60]
# Write your answer here
marks[marks < 40]#AP24110010760

as 32 is less than 40 so it comes under fail

In [ ]:
(marks > 80).sum()#AP24110010760

count of students abv 80 marks using sum operator

In [ ]:
np.where(marks < 40, 0, marks)#AP24110010760

automatically replacing marks less than 40 to zeros using where()

## Part 12: Joining Arrays

In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])

np.concatenate([a,b])#AP24110010760


## Part 13: Splitting Arrays

In [ ]:
x=np.arange(12)

np.split(x,3)#AP24110010760


### Student Practice

1. Split `x` into 4 equal parts instead of 3.
2. Try `np.split(x, 5)` — this should fail. Read the error and explain in one sentence why splitting into 5 doesn't work for 12 elements.


In [ ]:
x = np.arange(12)#AP24110010760
np.split(x, 4)

Each contains 3 elements as 12÷4=3

In [ ]:
np.split(x, 5) #AP24110010760

we cant dicide it equally

# Part 14: Image Analysis Using NumPy

## Why this matters for ML

A digital image **is** a NumPy array — this is exactly the data format used to feed images into computer vision models (e.g. CNNs). Every preprocessing step you do below (resizing, cropping, normalizing pixel values, flipping for data augmentation) is a real step used in production ML image pipelines, not just a classroom exercise.

## Image Shape Guidelines

A colour image is represented as:

`(height, width, channels)`

Example: `512 x 512 x 3` means:
- Height = 512 pixels
- Width = 512 pixels
- RGB colour channels = 3

**Avoid very large images** — a `4000 x 4000 x 3` image has 48 million individual pixel values. That's a lot to process and display.

Recommended:
- Practice: 300x300 pixels
- Processing: 512x512 pixels


In [ ]:
from google.colab import files
#AP24110010760
uploaded = files.upload()


In [ ]:
# The 'uploaded' variable is a dictionary: {filename: file_bytes}
# This line grabs the filename automatically instead of you typing it by hand
image_filename = list(uploaded.keys())[0]
print("Uploaded file:", image_filename)#AP24110010760


> **Note:** the cell above only works in Google Colab. If you're running this notebook locally (Jupyter/VS Code), skip it and instead set `image_path = "your_local_file.jpg"` directly in the next cell.

Upload an image file and note its name below:

Image name:


In [ ]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt#AP24110010760

# TASK: Load your uploaded image and convert it to a NumPy array.
# 1. Open the image with PIL: Image.open(image_filename)
# 2. Convert it to a NumPy array with np.array(...)
# 3. Print its .shape

img_array = None  # replace this line with your code


## Image Display

**Do not print the complete image array** (it's thousands of numbers and unreadable). Instead:
- Use `image.shape` to check dimensions
- Use `plt.imshow(...)` to *see* the image visually

### Student Practice
Display your uploaded image using `plt.imshow()` and turn off the axis with `plt.axis("off")`.


In [ ]:
# Write your code here to display img_array
from google.colab import files
uploaded = files.upload()
image_filename = list(uploaded.keys())[0]
print("Uploaded file:", image_filename)
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt
img_array = None#AP24110010760

In [ ]:
from google.colab import files
uploaded = files.upload()
image_filename = list(uploaded.keys())[0]
print("Uploaded file:", image_filename)
from PIL import Image
import numpy as np#AP24110010760
import matplotlib.pyplot as plt
img_array = None
img = Image.open(image_filename)
img_array = np.array(img)
print("Image shape:", img_array.shape)
plt.imshow(img_array)
plt.axis("off")
plt.show() #ap24110010760

KeyboardInterrupt: 

## Image Cropping

### Student Practice
Crop the **center 200x200 region** of your image (not a random corner — think about how to calculate the center offset from `img_array.shape`), store it in a variable called `crop`, and display it.


In [ ]:
# Write your cropping code here
height, width = img_array.shape[:2]
start_y = (height - 200) // 2
start_x = (width - 200) // 2
crop = img_array[start_y:start_y + 200, start_x:start_x + 200]
plt.imshow(crop)
plt.axis("off")
plt.show()#AP24110010760

here with this we can get the exact centre coordinates (200*200) and the cropped image is stored and then displayed

### Quick demo: showing multiple images side by side

You'll want to display more than one image at once in the tasks below (e.g. two flipped versions, or three RGB channels). `plt.subplots()` lets you do this in a grid. Study this small example, then reuse the pattern.


In [ ]:
# Demo: showing 2 plots side by side using plt.subplots
fig, axes = plt.subplots(1, 2, figsize=(8,4))

axes[0].imshow(img_array)
axes[0].set_title("Original")
axes[0].axis("off")#AP24110010760

axes[1].imshow(img_array)
axes[1].set_title("Original (again, just for demo)")
axes[1].axis("off")

plt.show()


## Image Flipping

### Student Practice
Produce and display both a vertical flip and a horizontal flip of your image using slicing (`[::-1]`), without using any built-in flip function.


In [ ]:
# Write your flipping code here
vertical_flip = img_array[::-1, :]
horizontal_flip = img_array[:, ::-1]
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(vertical_flip)#AP24110010760
plt.title("Vertical Flip")
plt.axis("off")
plt.subplot(1, 2, 2)
plt.imshow(horizontal_flip)
plt.title("Horizontal Flip")
plt.axis("off")
plt.show()

image using NumPy slicing. [::-1, :] reverses the rows to create a vertical flip, then [:, ::-1] reverses the columns to create a horizontal flip.

## RGB Channel Analysis

RGB channels:

- 0 - Red
- 1 - Green
- 2 - Blue

### Student Practice
Extract the red, green, and blue channels separately, and display each one using `plt.imshow(channel, cmap="gray")` so you can see which areas of the image are strongest in each color.


In [ ]:
# Write your RGB channel code here
red = img_array[:, :, 0]#AP24110010760
green = img_array[:, :, 1]
blue = img_array[:, :, 2]
plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(red, cmap="gray")
plt.title("Red Channel")
plt.axis("off")
plt.subplot(1, 3, 2)
plt.imshow(green, cmap="gray")
plt.title("Green Channel")
plt.axis("off")
plt.subplot(1, 3, 3)
plt.imshow(blue, cmap="gray")
plt.title("Blue Channel")
plt.axis("off")
plt.show()

like this we separate the image into Red, Green, and Blue colours using NumPy indexing. Each colour is displayed separately in grayscale to show the intensity of that particular color across the image.

## Brightness Analysis

### Student Practice
Calculate the average brightness of your image using `np.mean()`. Then calculate the average brightness of just the red channel, just the green channel, and just the blue channel. Which channel is brightest? Write your answer below the code.


In [ ]:
# Write your brightness code here
average_brightness = np.mean(img_array)
red_brightness = np.mean(img_array[:, :, 0])
green_brightness = np.mean(img_array[:, :, 1])
blue_brightness = np.mean(img_array[:, :, 2])
print("Average brightness:", average_brightness)
print("Red channel brightness:", red_brightness)
print("Green channel brightness:", green_brightness)
print("Blue channel brightness:", blue_brightness)
brightest = max(
    [("Red", red_brightness),
     ("Green", green_brightness),
     ("Blue", blue_brightness)],
    key=lambda x: x[1]
)
print("Brightest channel:", brightest[0]) #AP24110010760

np.mean() used to calculate the average brightness of the entire image and each RGB colour . It compares the three colour values to check which color colour is the brightes

*Your answer:*The channel with the highest average value is the brightest channel. Check the three printed values to identify whether it is red, green, or blue.


## Thresholding

Convert the image into pure black-and-white using `np.where()`.

### Student Practice
1. Convert the image to grayscale by averaging the 3 channels (`axis=2`).
2. Use `np.where(gray > 128, 255, 0)` to create a binary (black/white) version.
3. Display the result.
4. Try a different threshold (e.g. 100 or 180) and observe how it changes the result.


In [ ]:
gray = np.mean(img, axis=2)
binary = np.where(gray > 128, 255, 0)
plt.imshow(binary, cmap="gray")
plt.axis("off")
plt.show()#AP24110010760
binary_180 = np.where(gray > 180, 255, 0)
plt.imshow(binary_180, cmap="gray")
plt.axis("off")
plt.show()

we will 1st change RGB img into graycolur then with np.where() we will change gray img to black and white on selected threshhold

# Mini Project: Image Analyzer

Write a single program (you can reuse code from above) that prints/displays all of the following for your uploaded image, in order:

1. Image height, width, and number of channels
2. Average brightness (overall, and per channel)
3. The cropped center region
4. Both flipped versions (vertical and horizontal)
5. All 3 RGB channels shown separately
6. The thresholded (black/white) version

### Self-check before you submit
- [ ] I wrote the code myself rather than only uncommenting given code
- [ ] I can explain what every line does, not just that it runs
- [ ] My image display uses `plt.axis("off")` and looks correct
- [ ] I answered all reflection questions in my own words

## Reflection Questions

1. Why is NumPy faster than Python lists? (Refer back to your Part 1 answer — refine it if needed.)
Answer:numpy is faster cause array is stored in contiguos way and performs using optimization.where lists reference to each obj .

2. Explain broadcasting with an example of your own.
Answer:
it is ntg but doing operations bw array of diffrent but compatable shapes
3. What does image shape `(512,512,3)` represent?
Answer:
 512 image height (rows) 512 image width (columns) 3 three color channels: Red, Green, and Blue (RGB

4. Why should we avoid printing complete image arrays?
Answer:
if we produce whole img it will become difficult to read the o/p as tyhere will be so many pixel values

5. Explain RGB channels.
Answer:
RGB stands for red blue green each pixel contains 3 intensity values usually from 0 to 255 diffrent combinations of theese colurs form diff colurs

6. Where might you use this exact image-array workflow in a real machine learning project (e.g. what comes right before feeding an image into a CNN)?
Answer:
Tthis is used during image processing before feeding images into a CNN.


In [ ]:
height, width = img_array.shape[:2]
channels = img_array.shape[2]
print("Image Height:", height)
print("Image Width:", width)
print("Number of Channels:", channels)
average_brightness = np.mean(img_array)#AP24110010760
red_brightness = np.mean(img_array[:, :, 0])
green_brightness = np.mean(img_array[:, :, 1])
blue_brightness = np.mean(img_array[:, :, 2])
print("\nAverage Brightness:", average_brightness)
print("Red Brightness:", red_brightness)
print("Green Brightness:", green_brightness)
print("Blue Brightness:", blue_brightness)
start_y = (height - 200) // 2#AP24110010760
start_x = (width - 200) // 2
crop = img_array[start_y:start_y + 200, start_x:start_x + 200]
plt.figure()
plt.imshow(crop)
plt.title("Center Crop")
plt.axis("off")
plt.show()
vertical_flip = img_array[::-1, :]
horizontal_flip = img_array[:, ::-1]
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.imshow(vertical_flip)
plt.title("Vertical Flip")
plt.axis("off")
plt.subplot(1, 2, 2)
plt.imshow(horizontal_flip)
plt.title("Horizontal Flip")
plt.axis("off")
plt.show()
red = img_array[:, :, 0]
green = img_array[:, :, 1]
blue = img_array[:, :, 2]
plt.figure(figsize=(12, 4))
plt.subplot(1, 3, 1)
plt.imshow(red, cmap="gray")
plt.title("Red Channel")
plt.axis("off")
plt.subplot(1, 3, 2)
plt.imshow(green, cmap="gray")
plt.title("Green Channel")
plt.axis("off")
plt.subplot(1, 3, 3)#AP24110010760
plt.imshow(blue, cmap="gray")
plt.title("Blue Channel")
plt.axis("off")
plt.show()
gray = np.mean(img_array, axis=2)
binary = np.where(gray > 128, 255, 0)
plt.imshow(binary, cmap="gray")
plt.title("Thresholded Image")
plt.axis("off")
plt.show()

# Part 15: Text Analysis Using NumPy (NLP Track)

## Why this matters for ML/NLP

Before any NLP model (sentiment classifier, spam detector, chatbot) can process text, the text must be converted into numbers — this is called **vectorization**. NumPy arrays are the underlying data structure for almost every text representation: word counts, one-hot vectors, TF-IDF vectors, and even word embeddings are all just NumPy (or NumPy-like) arrays.

In this section, you'll build a small text analysis pipeline entirely with NumPy — no external NLP libraries — so you understand what's actually happening under the hood before you use libraries like `scikit-learn` or `nltk` later in the course.


## Step 1: From Text to Tokens

The first step in any NLP pipeline is **tokenization** — splitting text into individual words.

### Demonstration


In [ ]:
sentence = "NumPy makes numerical computing fast and NumPy makes arrays powerful"

# Basic tokenization: lowercase + split on spaces
tokens = sentence.lower().split()#AP24110010760
print(tokens)


### Student Practice

Tokenize this sentence the same way: `"Data Science and Machine Learning use NumPy arrays every single day"`. Store the result in a variable called `tokens2`.


In [ ]:
# Write your answer here
sentence2 = "Data Science and Machine Learning use NumPy arrays every single day"
tokens2 = sentence2.split()
print(tokens2)#AP24110010760

here we have used split() to divide the scentence into individual words stores the result in token2

## Step 2: Building a Vocabulary

A **vocabulary** is the set of all unique words across your text(s). We'll use `np.unique()` — the same function idea you used earlier for arrays of numbers, now applied to an array of words.


In [ ]:
tokens_array = np.array(tokens2)
vocabulary = np.unique(tokens_array)
print("Vocabulary:", vocabulary)
print("Vocabulary size:", len(vocabulary))#AP24110010760


### Student Practice

Build the vocabulary for `tokens2` from Step 1. How many unique words does it contain?


In [ ]:
# Write your answer here
vocabulary = set(tokens2)#AP24110010760
# AP24110010760
unique_words = len(vocabulary)
print("Vocabulary:", vocabulary)
print("Number of unique words:", unique_words)

here we have converted tokens2 into set then removed duplicates then uses len() to count unique words.

## Step 3: Word Frequency Vector (Bag-of-Words)

A **bag-of-words** vector represents a sentence as an array of word counts, one count per vocabulary word — this ignores word order but captures *what* words appear and *how often*.

### Demonstration: build a word-count vector by hand using NumPy


In [ ]:
def bag_of_words_vector(tokens2, vocabulary):
    # For each word in the vocabulary, count how many times it appears in tokens
    vector = np.array([np.sum(np.array(tokens2) == word) for word in vocabulary])
    return vector

vec = bag_of_words_vector(tokens2, vocabulary)
print(vocabulary)#AP24110010760
print(vec)


### Student Practice — predict then check

Before running, predict: which word(s) will have a count of 2 in the vector above? (Hint: look back at the original sentence — which word repeats?)

*Your prediction:*

Now build the bag-of-words vector for `tokens2` using its own vocabulary, and check your prediction concept applies the same way.


In [ ]:
vocabulary2 = list(set(tokens2))
bow_vector = [tokens2.count(word) for word in vocabulary2]
print("Vocabulary:", vocabulary2)
print("Bag-of-Words vector:", bow_vector)#AP24110010760

Prediction No word will have a count of 2 cause every word in sentence appears only once.

## Step 4: Comparing Two Sentences (Cosine Similarity)

Once text is turned into number vectors, we can measure how *similar* two sentences are using **cosine similarity** — a formula you'll see constantly in NLP and recommendation systems:

$$\text{cosine similarity} = \frac{A \cdot B}{\|A\| \times \|B\|}$$

This measures the angle between two vectors, not their length — so it works even if one sentence is longer than another.

### Demonstration


In [ ]:
sentence_a = "machine learning uses numpy arrays"
sentence_b = "deep learning also uses numpy arrays heavily"
tokens_a = sentence_a.lower().split()
tokens_b = sentence_b.lower().split()
#AP24110010760
# Build a shared vocabulary from both sentences combined
combined_vocab = np.unique(np.array(tokens_a + tokens_b))
vec_a = bag_of_words_vector(tokens_a, combined_vocab)
vec_b = bag_of_words_vector(tokens_b, combined_vocab)
print("Vector A:", vec_a)
print("Vector B:", vec_b)
# Cosine similarity using NumPy dot product and norm
cosine_sim = np.dot(vec_a, vec_b) / (np.linalg.norm(vec_a) * np.linalg.norm(vec_b))
print("Cosine similarity:", cosine_sim)

### Student Practice

Pick two sentences of your own (write them below) — one pair that should be *similar* in meaning/topic, and one pair that should be *very different*. Compute the cosine similarity for both pairs and confirm your intuition matches the numbers.


In [ ]:
# Write your answer here
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
sentence1 = "I love learning Python programming"
sentence2 = "I enjoy studying Python programming"
sentence3 = "The cat is sleeping on the sofa"#AP24110010760
sentence4 = "The weather is sunny today"
vectorizer = CountVectorizer()
vectors = vectorizer.fit_transform([sentence1, sentence2, sentence3, sentence4])
similar_pair = cosine_similarity(vectors[0], vectors[1])[0][0]
different_pair = cosine_similarity(vectors[2], vectors[3])[0][0]
print("Similarity of similar sentences:", similar_pair)
print("Similarity of different sentences:", different_pair)

**Reflection:** In your own words, why does cosine similarity give a value close to 1 for similar sentences and close to 0 for unrelated sentences? What would a `cosine similarity` of exactly 1 mean about two vectors?

*Your answer:*Cosine similarity tells the direction of two vectors. Similar sentences contain more common words, so their vectors point in similar directions and the value is closer to 1. Unrelated sentences have fewer common words, so their vectors are more different and the value is closer to 0.


## Step 5: Most Frequent Words

### Student Practice

Take any paragraph of your choice (3-4 sentences, write it below as a string). Then:
1. Tokenize it.
2. Build its vocabulary and word-count vector (reuse `bag_of_words_vector`).
3. Use NumPy to find and print the **top 3 most frequent words** (hint: look at sorting — `np.argsort()` sorts indices by value, and slicing with `[::-1]` reverses order).


In [ ]:
# Write your answer here
import numpy as np
paragraph = """
Python is a powerful programming language.
Python is easy to learn and Python is widely used.
Programming with Python helps students learn data science.
"""
tokens = paragraph.lower().split()#AP24110010760
vocabulary = list(set(tokens))
bag_of_words_vector = np.array([tokens.count(word) for word in vocabulary])
sorted_indices = np.argsort(bag_of_words_vector)[::-1]
top_3_indices = sorted_indices[:3]
print("Top 3 most frequent words:")
for i in top_3_indices:
    print(vocabulary[i], ":", bag_of_words_vector[i])

1st we do tokenaise the para then turn into vocab then counts how often each word appears . np.argsort() is udes to sort word by indices by frequency and display top 3 most frequent words.

# Mini Project: Simple Text Similarity Checker (NLP Track)

Build a small program that:

1. Takes **three** short sentences of your choice (write them as strings).
2. Tokenizes all three and builds one shared vocabulary across all of them.
3. Converts each sentence into a bag-of-words vector using that shared vocabulary.
4. Computes cosine similarity between every pair of sentences (3 pairs total: 1-2, 1-3, 2-3).
5. Prints which two sentences are the **most similar** to each other, based on the highest cosine similarity score.

### Self-check before you submit
- [ ] I wrote my own three sentences (not copied from the notebook)
- [ ] I can explain what a bag-of-words vector represents, in my own words
- [ ] I can explain why cosine similarity works even when sentences are different lengths
- [ ] My program correctly identifies and prints the most similar pair

## Reflection Questions (NLP Track)

1. Why do we need to convert text into numbers before a machine learning model can use it?

ML models works with numerical data converting text into number allows the models to perform operations and find patterns in text

2. What information does a bag-of-words vector *lose* about the original sentence? (Hint: think about what `split()` and counting alone doesn't capture.)

 It loses the word order and context of the sentence. It only records which words appear and how many times they occur

3. Why might cosine similarity be a better similarity measure than simply comparing raw word-count differences?

Cosine similarity compares the direction of the vectors rather than their size. Therefore, sentences with different lengths can still be considered similar if they have similar word patterns

4. Name one real-world application that likely uses something like this text-vectorization + similarity approach (e.g. search engines, plagiarism checkers, recommendation systems — pick one and explain briefly).


Search engines can convert a user's query and available documents into numerical vectors and compare them using similarity measures. Documents with vectors more similar to the query can be ranked higher in the search results.




In [ ]:
import numpy as np
sentence1 = "I love learning Python programming"
sentence2 = "I enjoy learning Python programming"
sentence3 = "The cat is sleeping on the sofa"
tokens1 = sentence1.lower().split()
tokens2 = sentence2.lower().split()#AP24110010760
tokens3 = sentence3.lower().split()
vocabulary = list(set(tokens1 + tokens2 + tokens3))
vector1 = np.array([tokens1.count(word) for word in vocabulary])
vector2 = np.array([tokens2.count(word) for word in vocabulary])
vector3 = np.array([tokens3.count(word) for word in vocabulary])
def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))
similarity_12 = cosine_similarity(vector1, vector2)
similarity_13 = cosine_similarity(vector1, vector3)
similarity_23 = cosine_similarity(vector2, vector3)
print("Similarity (Sentence 1, Sentence 2):", similarity_12)
print("Similarity (Sentence 1, Sentence 3):", similarity_13)
print("Similarity (Sentence 2, Sentence 3):", similarity_23)
scores = {
    "Sentence 1 & Sentence 2": similarity_12,
    "Sentence 1 & Sentence 3": similarity_13,
    "Sentence 2 & Sentence 3": similarity_23#AP24110010760
}
most_similar_pair = max(scores, key=scores.get)
print("\nMost similar pair:", most_similar_pair)
print("Similarity score:", scores[most_similar_pair])